version: '3'

services:
  app-staging:
    image: ${APP_IMAGE_STG}:latest
    container_name: app-staging
    environment: 
      - PORT=8080
    networks: 
      - my-net
    restart: always
networks:
  my-net:
    external: true