version: '3'

services:
  app-production:
    image: dharmatkj/app-typescript:latest
    container_name: app-production
    environment: 
      - PORT=8080
    ports:
      - "8080:8080"
    #networks: 
    #  - envoy
    restart: always
#networks:
#  envoy:
#    external: true
